### ISSUE TITLE
Add error check in create user

### ISSUE THREAD

**Issue by clairealmozinos** [EIP-SAM/SAM-Solution-Node-js#303]
## TODO
- [x] live check password confirmation.
- [x] check server error when wrong email.
- [x] check server error when wrong username.
