### ISSUE TITLE
Add horizontal navbar

### ISSUE THREAD

**Issue by vuongc** [EIP-SAM/SAM-Solution-Node-js#348]
## TODO
- [x] Add horizontal navbar
- [x] Make it responsive design
- [x] Adapt the content under the new navbar
