### ISSUE TITLE
Create a dashboard page

### ISSUE THREAD

**Issue by vuongc** [EIP-SAM/SAM-Solution-Node-js#349]
## TODO
- [x] Add dashboard route
- [x] Add dashboard link in he navbar
- [x] Create the dashboard container
- [x] Create the dashboard component
