### ISSUE TITLE
User dashboard

### ISSUE THREAD

**Issue by clairealmozinos** [EIP-SAM/SAM-Solution-Node-js#359]
## TODO
- [x] link in /users
- [x] username
- [x] link to edit user
- [x] button reboot
- [x] 5 last logs
- [x] save
  - [x] 3 last saves
  - [x] button instant save
  - [x] button scheduled save
- [x] restore
  - [x] 3 last restores
  - [x] button instant restore
