### ISSUE TITLE
Buttons in software by user page

### ISSUE THREAD

**Issue by clairealmozinos** [EIP-SAM/SAM-Solution-Node-js#422]
###TODO
- [x] button install all
- [x] button update all
- [x] button delete all
